config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'portfolio#home'
  get 'projects' => 'portfolio#projects'
  get 'skills' => 'portfolio#skills'
  get 'about' => 'portfolio#about'
  get 'close' => 'portfolio#close'
  get 'coders_handbook' => 'portfolio#coders_handbook'
  root 'portfolio#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController

  def home
  end

  def projects
  end

  def skills
  end

  def about
  end

  def coders_handbook
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/portfolio/_about.html.erb
<div id="about-wrapper" class="stacked-container AJAX-close-wrapper">
  <%= render 'body' %>
  <%= render 'image' %>
  <%= render 'social' %>
</div>

app/views/portfolio/_body.html.erb
<!-- Body -->
<div id="body-wrapper" class="stacked-container">
  <h1 class="large-text">Blaine Anderson</h1>
  <h3 class="med-text">Software Engineer | Web Developer</h3>
  <div class="small-text">
    <p class="text">Hey There! I'm Blaine Anderson, A Software Engineer & Web Developer based out of Mesa, Arizona. You can usually find me on a plethora of projects or working remotely for clients all over the world. </p>
  </div>
</div>

app/views/portfolio/_coders_handbook.html.erb
<div id="handbook-wrapper" class="AJAX-close-wrapper">
  <div class="handbook-intro">
    <h1 class="handbook-title">Coder's Handbook & Guides</h1>
    <h3 class="handbook-text">Time to time I find I need or would enjoy a guide to help me figure somthing out, usually something simple.
    It seems like creating a simple codex of common use lines of code, tips and tricks would be something you can find anywhere...</h3>
    <h3 class="handbook-text">No. No, finding it is the hard part. Most times the information I'm looking for is buried in a pile of filler for an article, or some small unimportant part is debated on stackoverflow, overshadowing the actual line of code needed for a project.</h3>
    <h3 class="handbook-text">Listed below are links to my own personal guides, filled with simple code blocks and minor notes including only pertinant information for the coder looking at it. I add to these guides as required, and have more in the works that are not listed here yet (not enough infomation included to be a whole guide).</h3>
    <h3 class="handbook-text">I hope that whoever finds this can use my guides to further their projects or resolve their errors.</h3>
  </div>
  <div class="handbook-link-container">
    <%= link_to 'Coders Handbook', "https://github.com/BlaineAndersonDev/coders-handbook/blob/master/coder_installation_instructions.md#coders-installation-handbook", target: :_blank, class: 'handbook-link'  %>
    <%= link_to 'Ruby On Rails Refresher', "https://github.com/BlaineAndersonDev/Rails5_2018_Skeleton#rails-5-skeleton", target: :_blank, class: 'handbook-link'  %>
    <%= link_to 'ReactJS Notes', "https://github.com/BlaineAndersonDev/Portfolio/blob/master/NOTES.md#developer-notes--examples", target: :_blank, class: 'handbook-link'  %>
  </div>
</div>

app/views/portfolio/_image.html.erb
<!-- Image -->
<div id="image-wrapper" class="container">
<!-- <%= image_tag("Blaine_Profile_01.jpg", class: "portfolio-image") %> -->
<%= image_tag("Blaine_Profile_03.jpg", class: "portfolio-image") %>
</div>

app/views/portfolio/_index.html.erb
<div id="portfolio-wrapper">
  <div id="AJAX-wrapper">

    <!-- Navigation Bar -->
    <div id="navigation-wrapper" class="nav-container">
      <h1 class="nav-text nav-item">Home</h1>
      <h1 class="nav-text nav-item">Projects</h1>
      <h1 class="nav-text nav-item">Skills</h1>
    </div>

    <!-- Body -->
    <div id="body-wrapper" class="stacked-container">
      <h1 class="large-text">BlaineAndersonDev.com</h1>
      <div class="small-text">
        <p class="text">Howdy! I'm Blaine Anderson, A Software Engineer & Web Developer based out of Mesa, Arizona. You can usually find me on a plethora of projects or working remotely for clients all over the world. </p>
      </div>
      <div class="small-text">
        <p class="text">I have a diversified set of skill including:</p>
        <p class="text">Front-End [ HTML | CSS | Javascript | ReactJS | +More]</p>
        <p class="text">Back-End [ Ruby | Rails | Node | SQL/PG | +More]</p>
        <p class="text">and I am eager to learn more!</p>
      </div>
    </div>

    <!-- Image -->
    <div id="image-wrapper" class="container">
    <!-- <%= image_tag("Blaine_Profile_01.jpg", class: "portfolio-image") %> -->
    <%= image_tag("Blaine_Profile_02.jpg", class: "portfolio-image") %>
    </div>

    <!-- Social Media -->
    <div id="social-wrapper" class="scrunched-container">
      <!-- Email -->
      <div class="stacked-container social-container">
        <% email_subject = "Wanted to talk about a Engineering opportunity!" %>
        <% email_body = "Hello Blaine!" %>
        <% email_summery = "[Insert your message for me here!]" %>
        <% email_funny = " ♪┏(°.°)┛┗(°.°)┓┗(°.°)┛┏(°.°)┓ ♪ " %>
        <%= link_to "mailto:BlaineAndersonDev@Gmail.com?subject=#{email_subject}&body=#{email_body}%0D%0A%0D%0A#{email_summery}%0D%0A%0D%0A#{email_funny}", :class => 'social-link' do %>
        <%= image_tag("Email_512_512.png", :alt => "Social_Media_Email_Image", :class => "social-image") %>
        <% end %>
        <p class="text social-text">BlaineAndersonDev@Gmail.com</p>
      </div>
      <!-- LinkedIn -->
      <div class="stacked-container social-container">
        <% linkedin_url = "https://www.linkedin.com/in/blaineandersondev/"%>
        <%= link_to "#{linkedin_url}", target: :_blank, :class => 'social-link' do %>
          <%= image_tag("Linkedin_512_512.png", :alt => "Social_Media_LinkedIn_Image", :class => "social-image") %>
        <% end %>
        <p class="text social-text">linkedin.com/in/blaineandersondev/</p>
      </div>
      <!-- Github -->
      <div class="stacked-container social-container">
        <% guthub_url = "https://github.com/BlaineAndersonDev"%>
        <%= link_to "#{guthub_url}", target: :_blank, :class => 'social-link' do %>
          <%= image_tag("Github_512_512.png", :alt => "Social_Media_Github_Image", :class => "social-image") %>
        <% end %>
        <p class="text social-text">github.com/BlaineAndersonDev</p>
      </div>
      <!-- Phone -->
      <div class="stacked-container social-container">
        <% phone_number = "4803053307"%>
        <%= link_to "#{linkedin_url}", target: :_blank, :class => 'social-link' do %>
          <%= image_tag("Phone_512_512.png", :alt => "Social_Media_Phone_Image", :class => "social-image") %>
        <% end %>
        <p class="text social-text">480-305-3307</p>
      </div>
      <div class="show-off"></div>
    </div>
  </div>
</div>

app/views/portfolio/_nav.html.erb
<!-- Navigation Bar -->
<div id="navigation-wrapper" class="nav-container">
  <%= link_to 'Home', about_path, remote: true, class: 'nav-link'  %>
  <%= link_to 'Projects', projects_path, remote: true, class: 'nav-link'  %>
  <%= link_to 'Skills', skills_path, remote: true, class: 'nav-link'  %>
  <%= link_to 'Coders Handbook', coders_handbook_path, remote: true, class: 'nav-link'  %>
</div>

app/views/portfolio/_projects.html.erb
<div id="projects-wrapper" class="AJAX-close-wrapper">

    <div class="project-item">
      <div class="project-item-left">
        <%= link_to "https://senyours.io/", target: :_blank, class: 'project-name' do %>
            <%= image_tag("SenYours_logo.jpg", class: "project-image") %>
        <% end %>
      </div>
      <div class="project-item-right">
        <%= link_to 'SenYours', "https://senyours.io/", target: :_blank, class: 'project-name' %>
        <p class="project-about">Senyours connect seniors with verified and background checked local citizens in their community to help with activities such as shopping, laundry, medical appointment and socialization for an hourly fee.</p>
        <p class="project-tech">Technologies: Rails, PG, HTML, CSS3, CarrierWave, Stripe, AJAX, JQuery, + More</p>
      </div>
    </div>

    <div class="project-divider"></div>

    <div class="project-item">
      <div class="project-item-left">
        <%= link_to "https://dungeons-battle-simulator.herokuapp.com/", target: :_blank, class: 'project-name' do %>
            <%= image_tag("dungeons_logo.jpg", class: "project-image") %>
        <% end %>
      </div>
      <div class="project-item-right">
        <%= link_to 'Dungeons', "https://dungeons-battle-simulator.herokuapp.com/", target: :_blank, class: 'project-name' %>
        <%= link_to 'Project Github', "https://github.com/BlaineAndersonDev/Dungeons", target: :_blank, class: 'project-github' %>
        <p class="project-about">A fully functional battle simulator, just like the Nintendo glory days. Includes a choice of characters and enemies.</p>
        <p class="project-tech">Technologies: ReactJS, Javascript, HTML, CSS3, React Routes, + More</p>
      </div>
    </div>

    <div class="project-divider"></div>

    <div class="project-item">
      <div class="project-item-left">
        <%= link_to "https://powerpostal.herokuapp.com/", target: :_blank, class: 'project-name' do %>
            <%= image_tag("power_postal_logo_2.png", class: "project-image") %>
        <% end %>
      </div>
      <div class="project-item-right">
        <%= link_to 'Power Postal', "https://powerpostal.herokuapp.com/", target: :_blank, class: 'project-name' %>
        <%= link_to 'Project Github', "https://github.com/BlaineAndersonDev/ProgressivePowerPostal", target: :_blank, class: 'project-github' %>
        <p class="project-about">From the ground up recreation of the original website. Include dynamic rendering & speedy response time.</p>
        <p class="project-tech">Technologies: ReactJS, Javascript, HTML, CSS3, React Routes, + More</p>
      </div>
    </div>

    <div class="project-divider"></div>

    <div class="project-item">
      <div class="project-item-left">
        <%= image_tag("sautee-seattle.png", class: "project-image") %>
      </div>
      <div class="project-item-right">
        <h1 class="project-name-nohover">Sautee Seattle</h1>
        <%= link_to 'Project Github', "https://github.com/Sautee-Seattle/Sautee-Seattle", target: :_blank, class: 'project-github' %>
        <p class="project-about">Created by a bunch of local foodies, Sautee Seattle focus' on local grown and sustainable produce. Provides an avenue for users to interact & locate local farmers markets as well as share recipies.</p>
        <p class="project-tech">Technologies: Rails, PG, HTML, CSS3, Selenium, Google API, AJAX, JQuery, + More</p>
      </div>
    </div>

    <div class="project-divider"></div>

</div>

app/views/portfolio/_skills.html.erb
<div id="skills-wrapper" class="stacked-container AJAX-close-wrapper">
  <h1 class="skill-title">My Skill Set</h1>
  <div class="skill-divider"></div>
  <div class="skill-container">
    <div class="skill-column">
      <h1 class="skill-item">Ruby</h1>
      <h1 class="skill-item">Ruby on Rails</h1>
      <h1 class="skill-item">RSpec</h1>
      <h1 class="skill-item">SimpleCov</h1>
      <h1 class="skill-item">CircleCI</h1>
      <h1 class="skill-item">Active Record</h1>
      <h1 class="skill-item">JQuery</h1>
      <h1 class="skill-item">AJAX</h1>
    </div>
    <div class="skill-column">
      <h1 class="skill-item">Javascript</h1>
      <h1 class="skill-item">ReactJS</h1>
      <h1 class="skill-item">React Routes</h1>
      <h1 class="skill-item">Jest</h1>
      <h1 class="skill-item">Enzyme</h1>
      <h1 class="skill-item">Node</h1>
      <h1 class="skill-item">Jasmine</h1>
      <h1 class="skill-item">Agile Workflow</h1>
    </div>
    <div class="skill-column">
      <h1 class="skill-item">HTML</h1>
      <h1 class="skill-item">CSS3</h1>
      <h1 class="skill-item">SQLite3</h1>
      <h1 class="skill-item">PostgreSQL</h1>
      <h1 class="skill-item">Sinatra</h1>
      <h1 class="skill-item">Stripe API</h1>
      <h1 class="skill-item">Google API</h1>
      <h1 class="skill-item">Team Management</h1>
    </div>
  </div>
  <div class="skill-divider"></div>
  <h1 class="skill-description">I am always seeking out additional knowledge,</h1>
  <h1 class="skill-description">so expect this list to expand over time!</h1>
</div>

app/views/portfolio/_social.html.erb
<!-- Social Media -->
<div id="social-wrapper" class="scrunched-container">
  <!-- Email -->
  <div class="stacked-container social-container">
    <% email_subject = "Wanted to talk about a Engineering opportunity!" %>
    <% email_body = "Hello Blaine!" %>
    <% email_summery = "[Insert your message for me here!]" %>
    <% email_funny = " ♪┏(°.°)┛┗(°.°)┓┗(°.°)┛┏(°.°)┓ ♪ " %>
    <%= link_to "mailto:BlaineAndersonDev@Gmail.com?subject=#{email_subject}&body=#{email_body}%0D%0A%0D%0A#{email_summery}%0D%0A%0D%0A#{email_funny}", :class => 'social-link' do %>
    <%= image_tag("Email_512_512.png", :alt => "Social_Media_Email_Image", :class => "social-image") %>
    <% end %>
    <p class="text social-text">BlaineAndersonDev@Gmail.com</p>
  </div>
  <!-- LinkedIn -->
  <div class="stacked-container social-container">
    <% linkedin_url = "https://www.linkedin.com/in/blaineandersondev/"%>
    <%= link_to "#{linkedin_url}", target: :_blank, :class => 'social-link' do %>
      <%= image_tag("Linkedin_512_512.png", :alt => "Social_Media_LinkedIn_Image", :class => "social-image") %>
    <% end %>
    <p class="text social-text">linkedin.com/in/blaineandersondev/</p>
  </div>
  <!-- Github -->
  <div class="stacked-container social-container">
    <% guthub_url = "https://github.com/BlaineAndersonDev"%>
    <%= link_to "#{guthub_url}", target: :_blank, :class => 'social-link' do %>
      <%= image_tag("Github_512_512.png", :alt => "Social_Media_Github_Image", :class => "social-image") %>
    <% end %>
    <p class="text social-text">github.com/BlaineAndersonDev</p>
  </div>
  <!-- Phone -->
  <div class="stacked-container social-container">
    <% phone_number = "4803053307"%>
    <%= image_tag("Phone_512_512.png", :alt => "Social_Media_Phone_Image", :class => "social-image") %>
    <p class="text social-text">480-305-3307</p>
  </div>
  <div class="show-off"></div>
</div>

app/views/portfolio/about.js.erb
$(".AJAX-close-wrapper").remove();
$("#AJAX-wrapper").append("<%=j render :partial => 'about' %>").hide().fadeIn(1000);

app/views/portfolio/close.js.erb
$(".AJAX-close-wrapper").remove();

app/views/portfolio/coders_handbook.js.erb
$(".AJAX-close-wrapper").remove();
 $("#AJAX-wrapper").append("<%=j render :partial => 'coders_handbook' %>").hide().fadeIn(1000);

app/views/portfolio/projects.js.erb
$(".AJAX-close-wrapper").remove();
 $("#AJAX-wrapper").append("<%=j render :partial => 'projects' %>").hide().fadeIn(1000);

app/views/portfolio/skills.js.erb
$(".AJAX-close-wrapper").remove();
 $("#AJAX-wrapper").append("<%=j render :partial => 'skills' %>").hide().fadeIn(1000);